bird(parrot).
bird(crow).
fish(whale).
hasfeet(elephant,4).
hasfeet(tiger,4).
hasfeet(parrot,2).
hasfeet(crow,2).
hasbackbone(whale).
hasbackbone(elephant).
eats(parrot,plant).
eats(crow,plant).
eats(elephant,plant).
eats(whale,plant).
eats(crow,animal).
eats(tiger,animal).
eats(whale,animal).
growswithmilk(whale).
growswithmilk(elephant).
largestanimal(elephant,land).
largestanimal(whale,sea).
quadruped(X):-hasfeet(X,4).
mammal(X):-growswithmilk(X),hasbackbone(X).
endothermic(X):-mammal(X).
omnivorous(X):-eats(X,plant),eats(X,animal).
